{% set name = "htchirp" %}
{% set version = "2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "3bcca4b809b81ea7b68acffed54104096437ea9aaf6063928120ad4c50cbd9f7"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - htchirp

about:
  home: "https://github.com/htcondor/htchirp"
  dev_url: "https://github.com/htcondor/htchirp"
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "Pure Python Chirp client for HTCondor"

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jasoncpatton
