travis:
  secure:
    BINSTAR_TOKEN: nC22WNSQP6zGbn1gSlbPK1DQPitqa+RjRN5D8WBOAROR4A3Y9DrcPxNzeEGFeJ+utu3kITH9TLl3wPrUFhWYOr2iuMki/vbommc20PTzYfoxQ9t0H8tZT36vOqhh50gqGvFofGaXTIWrb4f+pTso3ua+fuuIZjUWEN+DsDqbsu8rNR1AfVXApbA0n6Hw+wx5qzK8y5Adu3i/eB4V0kgkZ8RBcoEfAt21S4070W6gXQjP1ZRh1ihketI7CFen4w2CxFSxT+1FCSj057glKyXJVj8jCzz/7EaOV57NKXpyqS9mB6YHi5rhkAkhJA6PdVL1mmyFOQ6ADq2rb8xa/Edzd2rYB1T+lMPfgg+AoQO6IhkuHjpcEeD7WPo47yqUk4ATmfLyIJk5VvWzqX/i+lGJCWE+F4ywGnvvzpSk9tUo9HgC/N/fNlrhRr6TrlCpldlm/U7n9KmNxLRIQZIz17wK1BrgBK3wlUDxvfKaqxT3jSoovYpU1CDyaSfjeHDFXJ/+QQX07GLX6007Rbpi9dujowkDQOjAoe97m1Q0Nsyh9YQfqXbh+09OJoQJi2GCX6zHCkaKsh4S7d1/qOS4wXgciYuK4wO2Qgu47LFHDWuwd0xUP5wFoCm8OfBVnd/TN/aORjlZnFUwtY8oEPhVAUmXUqt7p2IxEsQAFf2EbJjXdSc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
